# coding: utf-8

"""


    Generated by: https://openapi-generator.tech
"""

import unittest
from unittest.mock import patch

import urllib3

import pdf_generator_api_client
from pdf_generator_api_client.paths.templates_template_id_copy import post  # noqa: E501
from pdf_generator_api_client import configuration, schemas, api_client

from .. import ApiTestMixin


class TestTemplatesTemplateIdCopy(ApiTestMixin, unittest.TestCase):
    """
    TemplatesTemplateIdCopy unit test stubs
        Copy template  # noqa: E501
    """
    _configuration = configuration.Configuration()

    def setUp(self):
        used_api_client = api_client.ApiClient(configuration=self._configuration)
        self.api = post.ApiForpost(api_client=used_api_client)  # noqa: E501

    def tearDown(self):
        pass

    response_status = 201




if __name__ == '__main__':
    unittest.main()
